version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: files
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./CRUD_service/scripts/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  worker:
    build: ./celery_service
    command: poetry run celery -A celery_worker.app worker
    volumes:
      - ./celery_service:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  crud_service:
    build:
      context: ./CRUD_service
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  celery_service:
    build:
      context: ./celery_service
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001

volumes:
  mongodb_data_container:
